= EUPORIAS API Guide
Work Package 44 - Delivery Tools;
:doctype: book
:icons: font
:source-highlighter: coderay
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
= Overview

The objective of http://www.euporias.eu/deliverables[Work Package 44] - Delivery Tools - is "to identify, develop, and maintain 
an interface which will allow an effective delivery of the climate services developed in WP 42 to both the general public and
the relevant decision-makers. In this manner, http://euporias.eu[EUPORIAS] goes beyond merely improving the reliability of the 
underlying prediction systems to enhancing the usability of these forecast in practical applications".

For this purpose, an API has been developed to deliver these outcomes in a homogeneous and standard way.

This page documents this API and provides some practical examples.

[[overview-http-verbs]]
== HTTP verbs

The EUPORIAS API tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview-http-status-codes]]
== HTTP status codes

The EUPORIAS API tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

[[overview-errors]]
== Errors

Whenever an error response (status code >= 400) is returned, the body will contain a JSON object
that describes the problem. The error object has the following structure:

include::{snippets}/error-example/response-fields.adoc[]

For example, a request that attempts to apply a non-existent tag to a note will produce a
`400 Bad Request` response:

include::{snippets}/error-example/http-response.adoc[]

[[overview-hypermedia]]
== Hypermedia

The EUPORIAS API uses hypermedia and resources include links to other resources in their
responses. Responses are in http://stateless.co/hal_specification.html[Hypertext Application
from resource to resource.
Language (HAL)] format. Links can be found beneath the `_links` key. Users of the API should
not create URIs themselves, instead they should use the above-described links to navigate

[[overview-security]]
== Security

The EUPORIAS API is secured following the Oauth2 protocol. Unless specified otherways all requests to the API 
must provide a valid authentication token. 

=== Token acquisition

A `GET` request is used to obtain a token. You must provide your credentials in this request. Each application has
associated a read write set of credentials, and a read only set of credentials. The application also has an administrator 
account.  

==== Example request

include::{snippets}/token-get-example/curl-request.adoc[]

==== Example response

include::{snippets}/token-get-example/http-response.adoc[]

=== Token usage

Once a valid token is obtained, you must provide your token in following requests as a header parameter. 

==== Example request

include::{snippets}/token-use-example/curl-request.adoc[]

==== Example response

include::{snippets}/token-use-example/http-response.adoc[]

[[resources]]
= Resources

[[resources-index]]
== Index

The index provides the entry point into the service.



[[resources-index-access]]
=== Accessing the index

A `GET` request is used to access the index

include::{snippets}/index-example/curl-request.adoc[]

==== Response structure

include::{snippets}/index-example/response-fields.adoc[]

==== Example response

include::{snippets}/index-example/http-response.adoc[]



[[resources-index-links]]
==== Links

include::{snippets}/index-example/links.adoc[]



[[resources-applications]]
== Applications

The Applications resources is used to create and manage applications and its associated products and parameters.


[[resources-applications-list]]
=== Listing applications

A `GET` request will list all of the service's notes.

==== Response structure

include::{snippets}/applications-list-example/response-fields.adoc[]

==== Example request

include::{snippets}/applications-list-example/curl-request.adoc[]

==== Example response

include::{snippets}/applications-list-example/http-response.adoc[]


[[resources-applications-create]]
=== Creating an application

A `POST` request is used to create an application

==== Request structure

include::{snippets}/applications-create-example/request-fields.adoc[]

==== Example request

include::{snippets}/applications-create-example/curl-request.adoc[]

==== Example response

include::{snippets}/applications-create-example/http-response.adoc[]

[[resources-applications-get]]
=== Details of an application

A `GET` request will list all of the application's details.

==== Response structure

include::{snippets}/applications-get-example/response-fields.adoc[]

==== Example request

include::{snippets}/applications-get-example/curl-request.adoc[]

==== Example response

include::{snippets}/applications-get-example/http-response.adoc[]


[[resources-applications-update]]
=== Updating an application

A `PUT` request is used to update an application. For example, we can modify an application's parameters for a certain product: 

==== Request structure

include::{snippets}/applications-update-example/request-fields.adoc[]

==== Example request

include::{snippets}/applications-update-example/curl-request.adoc[]

==== Example response

include::{snippets}/applications-update-example/http-response.adoc[]


[[resources-applications-delete]]
=== Deleting an application

A `DELETE` request is used to delete an application

==== Example request

include::{snippets}/applications-delete-example/curl-request.adoc[]

==== Example response

include::{snippets}/applications-delete-example/http-response.adoc[]




[[resources-outcomes]]
== Outcomes

The Outcomes resources is used to store and retrieve outcomes using its associated parameters.


[[resources-outcomes-create]]
=== Storing an outcome of file type

==== Creating the outcome

A `POST` request is used to create an outcome. Further requests will be necessary to store the results, as an attachment.

===== Request structure

include::{snippets}/outcomes-create-example/request-fields.adoc[]

===== Example request

include::{snippets}/outcomes-create-example/curl-request.adoc[]

===== Example response

include::{snippets}/outcomes-create-example/http-response.adoc[]

==== Attaching the file

===== Example request

include::{snippets}/outcomes-attach-example/curl-request.adoc[]

===== Example response

include::{snippets}/outcomes-attach-example/http-response.adoc[]

==== Retrieving the file

===== Example request

include::{snippets}/outcomes-attach-retrieve-example/curl-request.adoc[]

===== Example response

include::{snippets}/outcomes-attach-retrieve-example/http-response.adoc[]

==== Deleting the file

===== Example request

include::{snippets}/outcomes-attach-delete-example/curl-request.adoc[]

===== Example response

include::{snippets}/outcomes-attach-delete-example/http-response.adoc[]

=== Storing an outcome of embedded type

==== Creating the outcome

A `POST` request is used to create an outcome and store its contents. This type of outcomes show the results in the API calls directly (files will be encoded in Base64), and it's intended for texts or small files, such as small PNG graphs.   

===== Request structure

include::{snippets}/outcomes-create-embedded-example/request-fields.adoc[]

===== Example request

include::{snippets}/outcomes-create-embedded-example/curl-request.adoc[]

===== Example response

include::{snippets}/outcomes-create-embedded-example/http-response.adoc[]

=== Updating an outocome 

A `PUT` request is used to update an outcome.   

==== Request structure

include::{snippets}/outcomes-update-example/request-fields.adoc[]

==== Example request

include::{snippets}/outcomes-update-example/curl-request.adoc[]

==== Example response

include::{snippets}/outcomes-update-example/http-response.adoc[]

=== Deleting an outocome 

A `DELETE` request is used to delete an outcome.   

==== Example request

include::{snippets}/outcomes-delete-example/curl-request.adoc[]

==== Example response

include::{snippets}/outcomes-delete-example/http-response.adoc[]


=== Finding outocomes 

A `GET` request is used to retrieve outcomes.   

==== Response structure

include::{snippets}/outcomes-search-example/response-fields.adoc[]

==== Example request

include::{snippets}/outcomes-search-example/curl-request.adoc[]

==== Example response

include::{snippets}/outcomes-search-example/http-response.adoc[]

=== Finding outocomes metadata 

A `GET` request is used to explore available parameters values from the outcomes.   

==== Response structure

include::{snippets}/outcomes-search-meta-example/response-fields.adoc[]

==== Example request

include::{snippets}/outcomes-search-meta-example/curl-request.adoc[]

==== Example response

include::{snippets}/outcomes-search-meta-example/http-response.adoc[]

[[showcase]]
= Showcase

"The primary aim of the RESILIENCE prototype is to strengthen the efficiency and security of wind power supply within energy 
networks, by providing robust information of the future variability in wind power resources based on probabilistic climate 
predictions."
-- http://resilience.euporias.eu/en/resilience_overview,

The outcome of this prototype illustrates how seasonal wind predictions can lead to a safer, more efficient and therefore 
cost-effective operation and planning of wind power within the wider energy system. These outcomes are displayed through 
the http://project-ukko.net[UKKO project].

In the following sections we will show how to interact with the API to get the forecasts produced by RESILIENCE. To this aim, we will
build a web page displaying the forecasts over a map.

The source code is available at https://github.com/Predictia/resilience-demo[GitHub]. 

[[showcase-libraries]]
== Libraries
We will use the following libraries to build this example: 

* http://leafletjs.com[Leaflet]
* https://angularjs.org[Angular.js]
* http://www.pixijs.com[Pixi.js]
* https://github.com/ubilabs/kd-tree-javascript[k-d Tree JavaScript] 

[[showcase-products]]
== Products
RESILIENCE forecasts are stored in two different products:

* Global Forecast: a CSV file containing the forecasts for the world-wide. It has one parameter: the forecasts start date.
* Point Details: a JSON file containing the details for a particular grid-box. It has one parameter: the grid-box identifier.

[[showcase-token]]
== Getting a token
In order to get any outcome from the API it is needed a valid token. Therefore, we need to provide some information to get this token: 

[source,javascript]
----
var domain = "http://api.euporias.eu"; // <1>
var application = 6; // <2>
var user = "RESILIENCE.ro"; // <3>
var secret = "4e975e24-2124-4572-8b74-f6264907093e"; // <4>
----
<1> The URL where the API is deployed
<2> The RESILIENCE application ID in the API server
<3> The pre-defined user granted to read (and not to write) information from the application number 6
<4> The secret password for the user RESILIENCE.ro

With this information, we can make a post request to ask for a valid token. Following the http://oauth.net/2/[OAuth2] standard, the 
credentials are encoded in https://en.wikipedia.org/wiki/Base64[Base64]:

[source,javascript]
----
$http.defaults.useXDomain = true;
delete $http.defaults.headers.common['X-Requested-With'];
var postdata = 'grant_type=client_credentials&scope=read';
var authdata = "Basic "+Base64.encode(user + ':' + secret);
$http.post(domain+'oauth/token',postdata,{headers:{'Authorization':authdata,'Content-Type':'application/x-www-form-urlencoded'}})
  .then(function(response){
    d.resolve(response.data.access_token);
});
----

In the https://github.com/Predictia/resilience-demo/blob/master/js/script.js[complete example], the http://www.w3schools.com/html/html5_webstorage.asp[LocalStorage] is used in order to store a 
valid token and prevent unnecessary requests. So the complete OAuth2 authentication service will be: 

[source,javascript]
----
.factory('OauthService',function($http,$q,$base64,$localStorage){
 var user = "RESILIENCE.ro";
 var secret = "4e975e24-2124-4572-8b74-f6264907093e";
 $http.defaults.useXDomain = true;
 delete $http.defaults.headers.common['X-Requested-With'];
 return {
  token:function(){
   var d = $q.defer();
   var key = "resilience_access_token";
   var access_token = $localStorage[key];
   if((typeof access_token=='undefined' || angular.equals({},access_token)) || Date.now() > (access_token.expires_at - (600*1000))){
    var postdata = 'grant_type=client_credentials&scope=read';
    var authdata = "Basic "+Base64.encode(user + ':' + secret);
    $http.post(domain+'oauth/token',postdata,{headers:{'Authorization':authdata,'Content-Type':'application/x-www-form-urlencoded'}})
    .then(function(response){
      $localStorage[key] = {
       key:response.data.access_token,
       expires_at:Date.now()+(response.data.expires_in*1000)
      };
      d.resolve(response.data.access_token);
    });
   }else{
	 d.resolve(access_token.key);
   }
   return d.promise;
  }
 };
})
----

In the previous function, we use the https://docs.angularjs.org/api/ng/service/$q[$q] object following the http://wiki.commonjs.org/wiki/Promises[promise pattern].
This pattern will allow us to chain services easily.

[[showcase-metadata]]
== Getting metadata

In the following step we will get the most recent forecast. To do so, we use the `*outcomes/search/metadata*` facility 
giving `*forecastStartTime*` as parameter:

[source,javascript]
----
var queryMaxForecast = function(token){
 var d = $q.defer();
 $http.defaults.headers.common.Authorization = "Bearer "+token;
  getdata = "application="+application+"&product=Global Forecast&parameter=forecastStartTime";
  $http.get(domain+'outcomes/search/metadata?'+getdata)
   .then(function(response){
    var forecast = response.data._embedded.strings[0].content;
    d.resolve({token:token,forecast:forecast});
 });
 return d.promise;
};
----
Since the results are ordered from newest to oldest, we keep just the first item from the array.

[[showcase-global]]
== Getting the global forecast

Finally, with a valid token and a forecast time, we can ask for the global forecast CSV file:

[source,javascript]
----
var queryStations = function(token,forecastStartTime){
  var d = $q.defer();
  var key = "resilience_forecast-"+forecastStartTime;
  var globalForecast = $localStorage[key];
  if(typeof globalForecast=='undefined' || angular.equals({},globalForecast)){
   $http.defaults.headers.common.Authorization = "Bearer "+token;
    getdata = "application="+application+"&product=Global Forecast&forecastStartTime="+forecastStartTime;
    $http.get(domain+'outcomes/search/parameters?'+getdata)
     .then(function(response){
       $localStorage[key] = response.data._embedded.outcomes;
       d.resolve(response.data._embedded.outcomes);
     });
  }else{
   d.resolve(globalForecast);
  }
 return d.promise;
};
----

As in the token case, we use the http://www.w3schools.com/html/html5_webstorage.asp[LocalStorage] to prevent duplicated requests.

Since the results are encoded using Base64 we need to decoded them:
[source,javascript]
----
Base64.decode(data[0].results[0])
----

[[showcase-chain]]
== 
All of the previous steps make asynchronous request to get information from the API server. Angular.js makes easy to chain asynchronous request 
when they follow the promise pattern: 	 

[source,javascript]
----
GetStations:function(){
 return OauthService.token() // <1>
  .then(function(data){return queryMaxForecast(data)}) // <2>
  .then(function(data){return queryStations(data.token,data.forecast)}) // <3>
  .then(function(data){return Base64.decode(data[0].results[0])}); // <4>
},
----
<1> Gets a valid token (from the API or the LocalStorage)
<2> Gets the most recent forecast date
<3> Gets the global forecast CSV file
<4> Decodes the results 

[[showcase-details]]
== Station details

In the same way, we can easily build a service to fetch a detailed grid-box information given a grid-box id: 

[source,javascript]
----
var queryStationInfo = function(token,station){
 var d = $q.defer();
 $http.defaults.headers.common.Authorization = "Bearer "+token;
  getdata = "application="+application+"&product=Point Details&stationId="+station;
  $http.get(domain+'outcomes/search/parameters?'+getdata)
    .then(function(response){
      d.resolve(response.data._embedded.outcomes);
    });
  return d.promise;
};
----

[[showcase-ui]]
== User interface

Finally, the home controller will use the previous services to get the information and display it over a Leaflet map.
To do so, we use a canvas layer managed by Pixi.js to speed up the renderization process (there are several thousands of grid-boxes).
Clicking on a grid-box, a popup window with its detailed information (observation and forecasts) is displayed.
To resolve which grid-box is under a mouse event (mouseover or click), a https://en.wikipedia.org/wiki/K-d_tree[k-d Tree] is used.

The example is running http://predictia.github.io/resilience-demo[here].